version: "3"

services:
  backend:
    build:
      context: backend
    container_name: backend
    working_dir: /usr/app
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    tty: true
    ports:
      - "3003:3003"
    command: npm run start
    depends_on:
      - database
  frontend:
    build:
      context: frontend
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm run start
  database:
    image: mongo
    container_name: database
    command: mongod --quiet --logpath /dev/null
    restart: always
    tty: true
    ports:
      - 27017:27017
